config/routes.rb
Rails.application.routes.draw do
  root "static_pages#show", page_type: "home"

  get "static_pages/:page_type", to: "static_pages#show", as: "static_page"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show destroy)
  resources :posts, only: %i(create destroy) do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :relationships, only: %i(create destroy)
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: %i(create destroy)
  before_action :load_commentable
  before_action :verify_create, only: :create
  before_action :verify_destroy, only: :destroy

  def index
    @comments = @commentable.comments

    respond_to do |format|
      format.js
    end
  end

  def create
    @comment = @commentable.comments.build comment_params
    @comment.user_id = current_user.id

    if @comment.save
      respond_to {|format| format.js}
    end
  end

  def destroy
    @comment.destroy
    respond_to {|format| format.js}
  end

  private

  def comment_params
    params.require(:comment).permit :content
  end

  def load_commentable
    @post = Post.find_by id: params[:post_id] if params[:post_id]
    if params[:comment_id]
      @commentable = Comment.find_by id: params[:comment_id]
      return
    end
    @commentable = @post
  end

  def verify_create
    unless current_user.is_user?(@post.user) || current_user.following?(@post.user)
      flash[:danger] = t ".can_not_comment"
      redirect_to request.referrer || root_url
    end
  end

  def verify_destroy
    @comment = @commentable.comments.find_by id: params[:id]

    return if current_user.is_user?(@comment.user) || current_user.is_user?(@post.user)
    flash[:danger] = t ".can_not_delete"
    redirect_to request.referrer || root_url
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def commentable_type commentable
    commentable.class.name.downcase
  end
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>" class="comment">
  <li>
    <%= link_to gravatar_for(comment.user,
      size: Settings.comments.user.picture_size), comment.user %>
    <span class="user"><%= link_to comment.user.name, comment.user %></span>
    <span class="content"><%= comment.content %></span>
    <span class="timestamp">
      <%= t ".submit_at" %>
      <%= time_ago_in_words comment.created_at %>
      <%= t ".ago" %>
      <% if logged_in? && (current_user.is_user?(comment.user) ||
        current_user.is_user?(@post.user)) %>
        <% if comment.commentable_type == "Post" %>
          <%= link_to "delete", post_comment_path(commentable, comment),
            method: :delete, remote: true %>
        <% else %>
          <%= link_to "delete", comment_comment_path(commentable, comment,
            post_id: @post.id), method: :delete, remote: true %>
        <% end %>
      <% end %>
    </span>
    <span class="comment-manager">
      <%= link_to t(".reply"), comment_comments_path(comment, post_id: @post.id),
        remote: true %>
      <span class="badge" id="comment_<%= comment.id %>_comment_count">
        <%= comment.comments.size %>
      </span>
    </span>
    <ul class="comments-list" id="comment_<%= comment.id %>_comments"
      style="display: none">
    </ul>
    <% if logged_in? && (current_user.is_user?(@post.user) ||
      current_user.following?(@post.user)) && !current_user.is_user?(comment.user) %>
      <span id="comment_<%= comment.id %>_comment_form" style="display: none"
        class="comment-form"></span>
    <% end %>
  </li>
</div>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @commentable.comments.build], remote: true do |f| %>
  <% if commentable_type(@commentable) != "post" %>
    <%= hidden_field_tag :post_id, @post.id %>
  <% end %>
  <%= f.text_area :content, placeholder: t(".enter_comment") %>
  <%= f.submit t(".submit"), class: "btn btn-comment btn-primary" %>
<% end %>

app/views/comments/create.js.erb
$("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comments")
  .append("<%= escape_javascript(render @comment, commentable: @commentable) %>");
$("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comment_count")
  .html("<%= @commentable.comments.size %>");
$("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comment_form")
  .find('textarea').val('');

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").html("");
$("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comment_count")
  .html("<%= @commentable.comments.size %>");

app/views/comments/index.js.erb
if(<%= @commentable.comments.any? %>){
  $("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comments")
    .html("<%= escape_javascript(render @comments, commentable: @commentable) %>");
}
$("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comments")
  .toggle();
$("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comment_form")
  .toggle();
$("#<%= commentable_type @commentable %>_<%= @commentable.id %>_comment_form")
  .html("<%= escape_javascript(render 'comments/form') %>");