config/routes.rb
Rails.application.routes.draw do
  root "static_pages#show", page_type: "home"

  get "static_pages/:page_type", to: "static_pages#show", as: "static_page"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show destroy)
  resources :posts, only: %i(create destroy) do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to raw("<span class='glyphicon glyphicon-home'></span> " +
          t(".home")), root_path %></li>
        <li><%= link_to raw("<span class='glyphicon glyphicon-question-sign'>
          </span> " + t(".help")), static_page_path(:help) %></li>
        <% if logged_in? %>
          <li><%= link_to raw("<span class='glyphicon glyphicon-user'></span> "\
            + t(".users")), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t(".logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to raw("<span class='glyphicon glyphicon-log-in'>
            </span> " + t(".login")), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>